#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 DHI Android Build - Setup Status Check"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 Capacitor Packages:"
npm list @capacitor/core @capacitor/android 2>/dev/null | grep -E "@capacitor/(core|android)" || echo "   ❌ Not installed"
echo ""
echo "📱 Android Platform:"
ls -la android 2>/dev/null | head -5 || echo "   ❌ Not found"
echo ""
echo "⚙️  Config File:"
cat capacitor.config.ts 2>/dev/null | grep -E "appId|appName" || echo "   ❌ Not found"
echo ""
echo "📝 Scripts:"
cat package.json | grep -E "cap:|android:" || echo "   ❌ Not found"
echo ""
echo "🔄 Workflows:"
ls -la .github/workflows/ 2>/dev/null || echo "   ❌ Not found"
echo ""
echo "🚫 Gitignore:"
grep -q "android/build" .gitignore && echo "   ✅ Android entries present" || echo "   ❌ Missing"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
